# Generated by Django 3.1 on 2021-11-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoChat', '0001_initial'),
        ('ListaChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listchat',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GrupoChat.chat'),
        ),
    ]
