# Generated by Django 3.1 on 2021-12-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, null=True)),
                ('receiver', models.CharField(max_length=200, null=True)),
                ('mensaje', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Conversacion',
            },
        ),
    ]
